# This is an example Hyprland config file.
# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

# Please note not all available settings / options are set here.
# For a full list, see the wiki

# You can split this configuration into multiple files
# Create your files separately and then link them to this file like this:
# source = ~/.config/hypr/myColors.conf

# Monitors
source = ~/.config/hypr/modules/monitors.conf

# My Programs
source = ~/.config/hypr/modules/programs.conf

# Auto Start
source = ~/.config/hypr/modules/autostart.conf

# Environment Variabels
source = ~/.config/hypr/modules/env.conf

# Permissions
source = ~/.config/hypr/modules/permissions.conf

# Looks & Feels
source = ~/.config/hypr/modules/variables.conf

# Input
source = ~/.config/hypr/modules/input.conf

# Keybindings
source = ~/.config/hypr/modules/keybinds.conf

# Windows & Workspaces
source = ~/.config/hypr/modules/rules.conf